# Generated by Django 4.2 on 2023-04-24 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CadastroCliente', '0003_teste2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teste2',
        ),
    ]
