# Generated by Django 4.2 on 2023-04-25 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CadastroCliente', '0009_interesse_cliente_interesses'),
    ]

    operations = [
        migrations.AddField(
            model_name='telefone',
            name='nome',
            field=models.CharField(choices=[('Cel', 'Celular'), ('Res', 'Residencial'), ('Com', 'Comercial')], max_length=15, null=True),
        ),
    ]
