# Generated by Django 4.2 on 2023-04-25 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CadastroCliente', '0010_telefone_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telefone',
            name='nome',
        ),
    ]
